# Generated by Django 3.1.5 on 2021-05-01 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morale', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True)),
                ('top_goal', models.CharField(max_length=200, null=True)),
                ('highlights', models.CharField(max_length=200, null=True)),
                ('lowlights', models.CharField(max_length=200, null=True)),
                ('w_load', models.CharField(max_length=500, null=True)),
                ('goal_obs', models.CharField(max_length=100, null=True)),
                ('m_tip', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
