# Generated by Django 3.1.5 on 2021-05-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='YearsofExp',
        ),
    ]
