# Generated by Django 3.1.5 on 2021-05-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_remove_profile_yearsofexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='morale',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
